## ComfyUI-Manager: installing dependencies. (GitPython)
[2024-05-29 15:12] ## ComfyUI-Manager: installing dependencies done.
[2024-05-29 15:12] ** ComfyUI startup time: 2024-05-29 15:12:06.325149
[2024-05-29 15:12] ** Platform: Darwin
[2024-05-29 15:12] ** Python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
[2024-05-29 15:12] ** Python executable: /Users/jh/workspaces/sharosoo/comfyui/.venv/bin/python
[2024-05-29 15:12] ** Log path: /Users/jh/workspaces/sharosoo/comfyui/comfyui.log
[2024-05-29 15:12] 
Prestartup times for custom nodes:
[2024-05-29 15:12]    6.9 seconds: /Users/jh/workspaces/sharosoo/comfyui/custom_nodes/ComfyUI-Manager
[2024-05-29 15:12] 
Total VRAM 65536 MB, total RAM 65536 MB
[2024-05-29 15:12] pytorch version: 2.3.0
[2024-05-29 15:12] Set vram state to: SHARED
[2024-05-29 15:12] Device: mps
[2024-05-29 15:12] VAE dtype: torch.float32
[2024-05-29 15:12] Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[2024-05-29 15:12] ### Loading: ComfyUI-Manager (V2.35.1)
[2024-05-29 15:12] ### ComfyUI Revision: 2218 [28629cea] | Released on '2024-05-29'
[2024-05-29 15:12] Traceback (most recent call last):
  File "/Users/jh/workspaces/sharosoo/comfyui/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jh/workspaces/sharosoo/comfyui/custom_nodes/.git/__init__.py'

[2024-05-29 15:12] Cannot import /Users/jh/workspaces/sharosoo/comfyui/custom_nodes/.git module for custom nodes: [Errno 2] No such file or directory: '/Users/jh/workspaces/sharosoo/comfyui/custom_nodes/.git/__init__.py'
[2024-05-29 15:12] 
Import times for custom nodes:
[2024-05-29 15:12]    0.0 seconds (IMPORT FAILED): /Users/jh/workspaces/sharosoo/comfyui/custom_nodes/.git
[2024-05-29 15:12]    0.1 seconds: /Users/jh/workspaces/sharosoo/comfyui/custom_nodes/ComfyUI-Manager
[2024-05-29 15:12] 
[2024-05-29 15:12] Starting server

[2024-05-29 15:12] To see the GUI go to: http://127.0.0.1:8188
[2024-05-29 15:12] Exception in thread Thread-1 (<lambda>):
[2024-05-29 15:12] Traceback (most recent call last):
[2024-05-29 15:12]   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
[2024-05-29 15:12]     self.run()
[2024-05-29 15:12]   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
[2024-05-29 15:12]     self._target(*self._args, **self._kwargs)
[2024-05-29 15:12]   File "/Users/jh/workspaces/sharosoo/comfyui/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1667, in <lambda>
[2024-05-29 15:12]     threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
[2024-05-29 15:12]                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-05-29 15:12]   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
[2024-05-29 15:12]     return runner.run(main)
[2024-05-29 15:12]            ^^^^^^^^^^^^^^^^
[2024-05-29 15:12]   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
[2024-05-29 15:12]     return self._loop.run_until_complete(task)
[2024-05-29 15:12]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-05-29 15:12]   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
[2024-05-29 15:12]     return future.result()
[2024-05-29 15:12]            ^^^^^^^^^^^^^^^
[2024-05-29 15:12]   File "/Users/jh/workspaces/sharosoo/comfyui/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1664, in default_cache_update
[2024-05-29 15:12]     await asyncio.gather(a, b, c, d, e)
[2024-05-29 15:12]   File "/Users/jh/workspaces/sharosoo/comfyui/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1654, in get_cache
[2024-05-29 15:12]     with open(cache_uri, "w", encoding='utf-8') as file:
[2024-05-29 15:12]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-05-29 15:12] FileNotFoundError: [Errno 2] No such file or directory: '/Users/jh/workspaces/sharosoo/comfyui/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json'
[2024-05-29 15:12] 
Stopped server
